on:
	pull_request:
		types:	[opened, synchronize]
		branches:
			- main

jobs:
	build:
		runs-on: ubuntu-latest
		container: eclipse-temurin:21-jdk

		steps:
			-name: Clone repository
			 uses: actions/checkout@v4

			-name: Grant permissions to mvnw script
			 run: chmod +x mvnw

			-name: Run mvnw script
			 run: ./mvnw package

			-name: Save artifacts
			 uses: actions/upload-artifact@v4
			 with:
				name: rbpo_1
				path: ./target/rbpo_1-0.0.1-SNAPSHOT.jar