on:
    pull_request:
        types:    [opened, synchronize]
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        container: eclipse-temurin:21-jdk

        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Grant permissions to mvnw script
              run: chmod u+x ./mvnw

            - name: Run mvnw script
              run: ./mvnw package

            - name: Save artifacts
              uses: actions/upload-artifact@v4
              with:
                 name: rbpo_1
                 path: ./target/*.jar

#    sast-task:
#             name: SAST task
#             needs: build
#             runs-on: ubuntu-latest
#             container:
#               image: returntocorp/semgrep:latest
#    
#             steps:
#             - name: Clone repository
#               uses: actions/checkout@v4
#          
#             - name: Make directory
#               run: mkdir -p reports
#
#             - name: Run Semgrep Scan
#               run: |
#                 semgrep scan \
#                   --config "p/java" \
#                   --config "p/secrets" \
#                   --config "p/owasp-top-ten" \
#                   --output reports/semgrep-results.sarif \
#                   --sarif || true
#
#             - name: Save SARIF
#               uses: github/codeql-action/upload-sarif@v4
#               with:
#                 sarif_file: reports/semgrep-results.sarif
#
#             - name: Save results
#               uses: actions/upload-artifact@v4
#               with:
#                 name: semgrep-results
#                 path: reports/semgrep-results.sarif
#                 retention-days: 14
#
#    sca_task:
#             name: SCA Task
#             needs: build
#             runs-on: ubuntu-latest
#             container: eclipse-temurin:21-jdk
#             steps:
#             - name: Clone repository
#               uses: actions/checkout@v4
#        
#             - name: Make directory
#               run: mkdir -p reports
#
#             - name: Grant permissions to mvnw script
#               run: chmod +x ./mvnw
#
#             - name: Run OWASP Dependency-Check
#               run: |
#                 ./mvnw org.owasp:dependency-check-maven:check \
#                 -Dformat=HTML \
#                 -DoutputDirectory=reports \
#                 -DsuppressionFile=suppressions.xml || true
#
#             - name: Save reports
#               uses: actions/upload-artifact@v4
#               with:
#                 name: reports-owasp
#                 path: target/dependency-check-report.html
#                 retention-days: 14

    zap-baseline_scan:
        name: ZAP Baseline task
        needs: build
        runs-on: ubuntu-latest
        container:
          image: ghcr.io/zaproxy/zaproxy:latest
          options: --user root
        
        steps:
        - name: Clone repository
          uses: actions/checkout@v4
    
        - name: Install Java
          uses: actions/setup-java@v4
          with:
              java-version: '21'
              distribution: 'temurin'

        - name: Prepare ZAP Environment
          run: |
              sudo mkdir -p /zap/wrk
              sudo chown -R $USER:$USER /zap
              sudo chmod -R 755 /zap
    
        - name: Download app
          uses: actions/download-artifact@v4
          with:
            name: rbpo_1
            path: target/

        - name: Run application
          run: java -jar ./target/rbpo_1-0.0.1-SNAPSHOT.jar &
      
        - name: Wait for application to start
          run: sleep 30
    
        - name: ZAP baseline scan
          run: zap-baseline.py -t http://localhost:8080 -r report_site.html || true

        - name: ZAP reports
          run: cp /zap/wrk/report_site.html report_site.html
    
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: zap-baseline-report
            path: ./report_site.html
            retention-days: 14


    zap-api_scan:
        name: ZAP API Analysis
        needs: build
        runs-on: ubuntu-latest
        container:
          image: ghcr.io/zaproxy/zaproxy:latest
          options: --user root
    
        steps:
        - name: Clone repository
          uses: actions/checkout@v4
    
        - name: Install Java
          uses: actions/setup-java@v4
          with:
              java-version: '21'
              distribution: 'temurin'
    
        - name: Prepare ZAP Environment
          run: |
              sudo mkdir -p /zap/wrk
              sudo chown -R $USER:$USER /zap
              sudo chmod -R 755 /zap
    
        - name: Download app
          uses: actions/download-artifact@v4
          with:
            name: rbpo_1
            path: target/

        - name: Run application
          run: java -jar ./target/rbpo_1-0.0.1-SNAPSHOT.jar &
      
        - name: Wait for application to start
          run: sleep 30
    
        - name: ZAP-api scan
          run: zap-api-scan.py -t http://localhost:8080 -f openapi -r report_site.html || true

        - name: ZAP reports
          run: cp /zap/wrk/report_site.html report_site.html
    
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: zap-api-report
            path: ./report_site.html
            retention-days: 14
